### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by vrde** [urbi-mobility/ditto-contracts#2]
# User Stories

- [x] As Urbi Mobiliy, I want to deploy the `Registry` smart contract in production in the Ethereum Main Network.
  - [x] Instructions on how to generate an Ethereum account and put Ether in it.
  - [x] Documentation on how to mine the smart contract.
- [x] As Urbi Mobiliy, I want to deploy the `Registry` smart contract for testing in an Ethereum Test Network.
  - [x] Instructions on how to generate an Ethereum account and put Ether in it.
  - [x] Documentation on how to mine the smart contract.
- [x] As Urbi Mobility, I want to delegate to a Certification Authority the rights to add and revoke certifications.
  - [x] Code the support for `WhitelistAdminRole` and `WhitelistedRole` using the OpenZeppeling ACL library.
  - [x] Code CLI to manage ACLs.
  - [x] Test the CLI.
  - [x] Document how to use it.
- [x] As Urbi Mobility, I want to make sure I'm not going to lose access to the smart contract if something bad happens to my private key.
  - [x] Document how a MultiSig wallet can mitigate the attack surface.
- [x] As a Certification Authority (i.e. any address that has a `WhitelistedRole`), I want to add and revoke certifications.
  - [x] Code the logic to add and revoke certifications
  - [x] Test the logic.
  - [x] Document how to use it.
- [x] As a Provider, I want to verify the validity of a certification. (Don't trust, verify)
  - [x] Document the process to validate a proof stored in the smart contract.
- [x] As a Provider, I want to be notified when a certification has been revoked.
  - [x] Code a revoke event that is triggered when a certification is removed.
  - [x] Test it.
  - [x] Document the integration on the Provider side.
- [x] As the European Union, I demand that data subjects cannot be directly or indirectly identified
  - [x] Hash PPI (Private Personal Information) in a way that it's impossible to identify the data subject.
  - [x] Document the steps.
- [x] As a User, I want to be able to remove my data.
  - [x] Code an ACL to allow the user to remove the data.
  - [x] Test it.
